source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('<int:pk>/', UserDetailView.as_view(), name="detail")
]

source/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views.photos import IndexView, PhotoView, PhotoCreateView, TokenLinkView, PhotoDeleteView, PhotoTokenView,PhotoUpdateView, SelectedPhotoView, PhotoUnselectView
from webapp.views.albums import AlbumCreateView, AlbumDeleteView, AlbumDetailView, AlbumUpdateView
app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="view"),
    path('photo/add/', PhotoCreateView.as_view(), name="photo_add"),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name="delete_photo"),
    path('photo/<int:pk>/edit/', PhotoUpdateView.as_view(), name="edit_photo"),
    path('album/add/', AlbumCreateView.as_view(), name='album_add'),
    path('album/<int:pk>/update/', AlbumUpdateView.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('album/<int:pk>/', AlbumDetailView.as_view(), name="album_view"),
    path('photo/<int:pk>/select/', SelectedPhotoView.as_view(), name="select"),
    path('photo/<int:pk>/unselect/', PhotoUnselectView.as_view(), name="unselect"),
    path('photo/<int:pk>/token/', PhotoTokenView.as_view(), name='photo_token'),
    path('photo/<uuid:token>/token/', TokenLinkView.as_view(), name='token_link')

]

source/webapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()


class Photo(models.Model):
    picture = models.ImageField(null=False, blank=False, verbose_name='Photo', upload_to='uploads')
    caption = models.CharField(null=False, blank=False, verbose_name='Caption', max_length=100)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Creation date")
    author = models.ManyToManyField(
        User,
        related_name="photos",
        verbose_name="Author"
    )
    album = models.ForeignKey('webapp.Album', on_delete=models.CASCADE,
                              verbose_name="Album", null=True, blank=True, related_name='photos')
    is_private = models.BooleanField(default=False, verbose_name='Privacy')

    selected = models.ManyToManyField(
        User,
        related_name="selected_photos"
    )
    token = models.CharField(null=True, blank=True, max_length=200)


    class Meta:
        verbose_name = "Photo"
        verbose_name_plural = "Photos"

    def __str__(self) -> str:
        return f'{self.caption}'


class Album(models.Model):
    name = models.CharField(null=False, blank=False, verbose_name='Name', max_length=100)
    description = models.TextField(null=True, blank=True, verbose_name='Description', max_length=2000)
    author = models.ManyToManyField(
        User,
        related_name="albums",
        verbose_name="Author"
    )
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name="Creation date")
    is_private = models.BooleanField(default=False, verbose_name='Privacy')

    class Meta:
        verbose_name = "Album"
        verbose_name_plural = "Albums"

    def __str__(self) -> str:
        return f'{self.name}'

source/webapp/forms.py
from django import forms
from webapp.models import Photo, Album


class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ["picture", "caption", "album"]


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ["name", "description"]

source/webapp/views/albums.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from webapp.models import Photo, Album
from webapp.forms import AlbumForm
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse


class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    form_class = AlbumForm
    template_name = "albums/create.html"

    def form_valid(self, form):
        response = super(AlbumCreateView, self).form_valid(form)
        self.object.author.add(self.request.user)
        return response

    def get_success_url(self):
        return reverse('webapp:album_view', kwargs={'pk': self.object.pk})


class AlbumDeleteView(PermissionRequiredMixin, DeleteView):
    model = Album
    permission_required = 'webapp.delete_album'

    def get(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("webapp:index")

    def has_permission(self):
        super().has_permission() and self.get_object().author == self.request.user


class AlbumDetailView(LoginRequiredMixin, DetailView):
    template_name = 'albums/view.html'
    model = Album
    context_object_name = 'album'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        photos = self.object.photos.order_by("-created_at")
        author = self.object.author.all()
        context['photos'] = photos
        context['author'] = author
        return context


class AlbumUpdateView(PermissionRequiredMixin, UpdateView):
    model = Album
    template_name = 'albums/update.html'
    form_class = AlbumForm
    permission_required = 'webapp.change_album'

    def get_success_url(self):
        return reverse("webapp:album_view", kwargs={"pk": self.object.pk})

    def has_permission(self):
        super().has_permission() and self.get_object().author == self.request.user

source/webapp/views/photos.py
import uuid
from http import HTTPStatus

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from webapp.models import Photo
from webapp.forms import PhotoForm

# Create your views here.
class IndexView(LoginRequiredMixin, ListView):
    template_name = 'photos/index_view.html'
    context_object_name = 'photos'
    model = Photo
    ordering = ['-created_at']


class PhotoView(LoginRequiredMixin, DetailView):
    template_name = 'photos/view.html'
    model = Photo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if Photo.objects.filter(is_private=True):
            author = self.object.author.all()
            context['author'] = author
            selected_photos = self.object.selected.all()
            context['selected_photos'] = selected_photos
        return context


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    form_class = PhotoForm
    template_name = "photos/photo_add.html"

    def form_valid(self, form):
        response = super(PhotoCreateView, self).form_valid(form)
        self.object.author.add(self.request.user)
        return response

    def get_success_url(self):
        return reverse('webapp:view', kwargs={'pk': self.object.pk})


class PhotoDeleteView(PermissionRequiredMixin, DeleteView):
    model = Photo
    template_name = "photos/delete.html"
    success_url = reverse_lazy('webapp:index')
    context_object_name = 'photo'
    permission_required = 'webapp.delete_photo'

    def has_permission(self):
        super().has_permission() and self.get_object().author == self.request.user


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Photo
    form_class = PhotoForm
    template_name = "photos/edit_photo.html"
    context_object_name = 'photo'
    permission_required = 'webapp.change_photo'

    def get_success_url(self):
        return reverse('webapp:view', kwargs={"pk": self.object.pk})

    def has_permission(self):
        super().has_permission() and self.get_object().author == self.request.user


class SelectedPhotoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get("pk"))

        if request.user in photo.selected.all():
            return JsonResponse(
                {"error": "This photo has already been selected"},
                status=HTTPStatus.FORBIDDEN,
            )

        photo.selected.add(request.user)

        return JsonResponse(
            {"select_count": photo.selected.count()}
        )


class PhotoUnselectView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs.get("pk"))

        if not photo.selected.filter(id=request.user.id).exists():
            return JsonResponse(
                {"error": "You have to select first"},
                status=HTTPStatus.FORBIDDEN,
            )

        photo.selected.remove(request.user)
        return JsonResponse(
            {"select_count": photo.selected.count()}
        )


class PhotoTokenView(View):
    def get(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, pk=kwargs['pk'])
        token = uuid.uuid4()
        photo.token = token
        photo.save()
        return redirect('webapp:view', photo.pk)

class TokenLinkView(View):
    def get(self, request, *args, **kwargs):
        photo = get_object_or_404(Photo, token = kwargs['token'])
        context = {
            'photo': photo
        }
        return render(request, 'photos/view.html', context)

source/webapp/templates/photos/delete.html
{% extends "base.html" %}
{% block title %}Delete Photo{% endblock %}
{% block content %}
    <form action="{% url "webapp:delete_photo" photo.pk %}" method="POST">
    {% csrf_token %}
        <h2>Are you sure you want to delete {{ photo.caption }}?</h2>
        <input class="btn btn-primary mb-3" type="submit" value="YES">
    </form>
    <a class="btn btn-primary" href="{% url "webapp:index" %}">NO</a>
{% endblock %}

source/webapp/templates/photos/edit_photo.html
{% extends 'base.html' %}
{% block title %}Update photo{% endblock %}
{% block nav %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webapp:view' photo.pk%}">Back to photo</a>
    </li>{% endblock %}
{% block content %}
    <h1>Update Photo</h1>
    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Edit"  %}
    </form>
{% endblock %}

source/webapp/templates/photos/index_view.html
{% extends 'base.html' %}
{% block content %}
    <h1 class="text-center">Photos</h1>
 {% for photo in photos %}
     <div class="card" style="width: 25rem;">
      <img class="photo" src="{{ photo.picture.url }}" alt="photo">
       {% include "partial/selected_photos.html" %}
     <div class="card-body">
         <p class="card-text"> Caption: {{ photo.caption }}</p>
         <p class="card-text"> Author: {{ photo.author.username }}</p>
           {% if photo.album %}
         <a href="{% url 'webapp:album_view' photo.album.pk %}"><p class="card-text"> Album: {{ photo.album }}</p></a>
         {% endif %}
         <p class="card-text"> Date: {{ photo.created_at }}</p>
     <a href="{% url 'webapp:view' photo.pk %}"><h4>Details</h4></a>
      {% if perms.webapp.change_photo %}
      <a href="{% url 'webapp:edit_photo' photo.pk %}"><h4>Edit</h4></a>
     {% endif %}
      {% if perms.webapp.delete_photo %}
     <a href="{% url 'webapp:delete_photo' photo.pk %}"><h4>Delete</h4></a>
     {% endif %}
  </div>
</div>
    {% endfor %}
     </div>
{% endblock %}

source/webapp/templates/photos/photo_add.html
{% extends 'base.html' %}

{% block title %}Create photo{% endblock %}
{% block nav %}{% endblock %}
{% block content %}
    <h1>Create New Photo</h1>

    <form method="post" enctype="multipart/form-data">
        {% include "partial/form.html" with button_text="Add" %}
    </form>
{% endblock %}

source/webapp/templates/photos/view.html
{% extends 'base.html' %}

{% block title %}Photo details {{ photo.pk }}{% endblock %}
{% block nav %}
{% endblock %}
{% block content %}
    {% if perms.webapp.change_photo %}
      <a href="{% url 'webapp:edit_photo' photo.pk %}"><h4>Edit</h4></a>
     {% endif %}
      {% if perms.webapp.delete_photo %}
     <a href="{% url 'webapp:delete_photo' photo.pk %}"><h4>Delete</h4></a>
     {% endif %}
     <img class="photo" src="{{ photo.picture.url }}" alt="photo">
    <p class="card-text"> Caption: {{ photo.caption }}</p>
           {% if photo.album %}
         <a href="{% url 'webapp:album_view' photo.album.pk %}"><p class="card-text"> Album: {{ photo.album }}</p></a>
         {% endif %}
         <p class="card-text"> Date: {{ photo.created_at }}</p>
    {% if selected_photos %}
        {% for a in selected_photos %}
         <a href="{% url 'accounts:detail' user.pk %}"><p class="card-text"> Users who selected: {{ a.username }}</p></a>
        {% endfor %}
    {% endif %}
    {% if photo.author == user %}
    {% if photo.token == None %}
        <a href="{% url 'webapp:photo_token' photo.pk %}"><p class="card-text"> Generate your token</p></a>
        {% else %}
        <a href="{% url 'webapp:token_link' photo.token %}"><p class="card-text">http://localhost:8000/photo/{{ photo.token }}/token/</p></a>
    {% endif %}
    {% endif %}
{% endblock %}