source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts.views import UserDetailView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('<int:pk>/', UserDetailView.as_view(), name="detail")
]

source/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from webapp.views.photos import IndexView, PhotoView, PhotoCreateView, TokenLinkView, PhotoDeleteView, PhotoTokenView,PhotoUpdateView, SelectedPhotoView, PhotoUnselectView
from webapp.views.albums import AlbumCreateView, AlbumDeleteView, AlbumDetailView, AlbumUpdateView
app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('photo/<int:pk>/', PhotoView.as_view(), name="view"),
    path('photo/add/', PhotoCreateView.as_view(), name="photo_add"),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name="delete_photo"),
    path('photo/<int:pk>/edit/', PhotoUpdateView.as_view(), name="edit_photo"),
    path('album/add/', AlbumCreateView.as_view(), name='album_add'),
    path('album/<int:pk>/update/', AlbumUpdateView.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', AlbumDeleteView.as_view(), name='album_delete'),
    path('album/<int:pk>/', AlbumDetailView.as_view(), name="album_view"),
    path('photo/<int:pk>/select/', SelectedPhotoView.as_view(), name="select"),
    path('photo/<int:pk>/unselect/', PhotoUnselectView.as_view(), name="unselect"),
    path('photo/<int:pk>/token/', PhotoTokenView.as_view(), name='photo_token'),
    path('photo/<uuid:token>/token/', TokenLinkView.as_view(), name='token_link')

]

source/accounts/models.py
from django.db import models

# Create your models here.

source/accounts/views.py
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import render
from django.views.generic import DetailView


class UserDetailView(DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 3
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        albums = self.get_object().albums.all()
        kwargs['albums'] = albums
        paginator = Paginator(
            self.get_object().photos.all(),
            self.paginate_related_by,
            self.paginate_related_orphans,
            )
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['photos'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super(UserDetailView, self).get_context_data(**kwargs)

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}User{% endblock %}
{% block content %}
    <h1>Personal page {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    <p>User name: {{ user_obj.username }}</p>
    {% if albums %}
        {% for album in albums %}
          <p class="card-text"> Name: {{ album.name }}</p>
           <p class="card-text"> Description: {{ album.description }}</p>
    <a href="{% url 'webapp:album_update' album.pk %}"><h4>Edit this album</h4></a>
     <a href="{% url 'webapp:album_delete' album.pk %}"><h4>Delete this album</h4></a>
        {% endfor %}
    {% endif %}
    {% if photos %}
        {% for photo in photos %}
          <img class="photo" src="{{ photo.picture.url }}" alt="photo">
        {% endfor %}
    {% endif %}
{% endblock %}